network: PolicyGMMLayer
network_kwargs:
  output_dim: 4
  num_layers: 2
  num_dim: 1024
  num_modes: 5
  min_std: 0.0001
  std_activation: "softplus"
  low_noise_eval: true
  activation: "relu"
  action_scale: 1.
  action_squash: true