name: BCTransformerPolicyRGB

defaults:
  - aug@color_aug: batch_wise_img_color_jitter_group_aug.yaml
  - aug@translation_aug: translation_aug.yaml
  - encoder@rgb_encoder: resnet_conv.yaml
  - projection@spatial_projection: spatial_projection.yaml
  - group: action_token_group_modalities.yaml
  - temporal_position: temporal_sin_position_encoding.yaml
  - transformer: transformer_decoder.yaml
  - policy_output_head: gmm_policy_mlp_layer
  



