
network: ActionTokenGroupModalities
network_kwargs:
  use_joints: false  
  use_gripper: true
  use_gripper_history: false
  use_ee_pos: false
  use_ee_ori: false
  embedding_size: 64
  ee_pos_dim: 3
  ee_ori_dim: 3
  joint_states_dim: 7
  gripper_states_dim: 2
  gripper_history_dim: 10
  zero_action_token: false
